.\" Manpage for lsf.
.TH lsf 1 "30 November 2020" "1.0" "lsf man page"
.SH NAME
lsf \- ls with filter
.SH SYNOPSIS
.TP
\fBlsf\fP [ -h ]
.TP
\fBlsf\fP [ -F | -D ] [ -m \fImode\fP ] [ -l \fIlinks\fP ] [ -U | -u \fIusername\fP ] [ -G | -g \fIgroupname\fP ] [ -b \fIsize\fP ] [ -T | -t \fIdays\fP ] [ -n \fIfilename\fP ] \fIdirname\fP
.SH DESCRIPTION
\fBlsf\fP filters the output of \fBls -al\fP based on the provided criteria.
.SS Options
.TP
\fB-h\fP
Display the usage help page and exit.
.TP
\fB-F\fP
Only display files.
.TP
\fB-D\fP
Only display directories.
.TP
\fB-m \fImode\fP
Only display results that match the octal permissions, \fImode\fP.
.TP
\fB-l \fIlinks\fP
Only display results that match the comparison string (e.g. ">=8" or "<90"), \fIlinks\fP, for the number of links to each.
.TP
\fB-U\fP
Only display results belonging to the current user.
.TP
\fB-u \fIusername\fP
Only display results belonging to a user matching the pattern, \fIusername\fP. The value of \fIusername\fP can be a normal string or regex, or it can be a comparison string representing the range of uid's that can be displayed (e.g. ">=20" or "=100").
.TP
\fB-G\fP
Only display results belonging to the current user's group.
.TP
\fb-g \fIgroupname\fP
Only display results belonging to a user of a group matching the pattern, \fIgroupname\fP. The value of \fIgroupname\fP can be a normal string or regex, or it can be a comparison string, representing the range of gid's that can be displayed (e.g. "=100" or "<40").
.TP
\fB-b \fIsize\fP
Only display results that match the comparison string, \fIsize\fP, for the size (in bytes) of each.
.TP
\fB-T\fP
Filter out all files and directories that have been modified as or more recently than 6 months ago.
.TP
\fB-t \fIdays\fP
Filter out all files and directories that have been modified as or more recently than \fIdays\fP days ago.
.TP
\fB-n \fIfilename\fP
Only display files matching the pattern, \fIfilename\fP, which can be either an exact string or a regex.
.SS Comparison Strings
For the purposes of this utility, a comparison string is essentially the right half of an inequality (where the attribute in question of each file is assumed to be the left half), defining the threshold for filtering files. Valid values are "!=", "=", "<", "<=", ">", and ">=", followed (without spaces) by the number to be compared to and enclosed in quotes.
.P
For example, if you wanted to limit results to files/directories in your home directory that have fewer than 15 links, you would run the utility as
.P
.IP
\fBlsf -l "<15" ~\fP.
.P
Or to display only files/directories in your home directory belonging to a user with uid 501, you would run the utility as
.P
.IP
\fBlsf -u "=501" ~\fP.
.SH "SEE ALSO"
ls(1)

